basePath: /api/v1
definitions:
  httputil.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
  topic.addTopicCommand:
    properties:
      id:
        example: 550e8400-e29b-41d4-a716-446655440000
        format: uuid
        type: string
      sprint:
        example: 550e8400-e29b-41d4-a716-446655440001
        format: uuid
        type: string
      text:
        example: a short topic description
        type: string
    type: object
  topic.topicModel:
    properties:
      id:
        example: 550e8400-e29b-41d4-a716-446655440000
        format: uuid
        type: string
      sprint:
        example: 550e8400-e29b-41d4-a716-446655440001
        format: uuid
        type: string
      text:
        example: a short topic description
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  license: {}
  title: Retro jar API
  version: "1.0"
paths:
  /topics:
    post:
      consumes:
      - application/json
      parameters:
      - description: Add topic
        in: body
        name: topic
        required: true
        schema:
          $ref: '#/definitions/topic.addTopicCommand'
          type: object
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
            type: object
      summary: create a new topic
  /topics/{sprint_id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Sprint ID
        in: path
        name: sprint_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/topic.topicModel'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
            type: object
      summary: list sprint topics
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
