version: '3.2'

services:
    proxy:
        image: nginx
        ports:
            - 8081:80
        volumes:
            - ./docker/proxy/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./client/dist:/client
        networks:
            - dev
    server:
        build: ./server
        networks:
            - dev

    client:
        build: ./client
        volumes:
            - ./client:/usr/src/app
        networks:
            - dev

networks:
    dev:
        driver: bridge
        attachable: true
