version: '3.2'

services:
    client:
        build: ./client
        image: 563026470921.dkr.ecr.eu-central-1.amazonaws.com/client
        ports:
            - 8080:80
        environment:
            - API_HOST=http://localhost:8081
        networks:
            - dev
    server:
        build: ./server
        image: 563026470921.dkr.ecr.eu-central-1.amazonaws.com/server
        ports:
            - 8081:8080
        networks:
            - dev

networks:
    dev:
        driver: bridge
        attachable: true
