version: '3.2'

services:
    client:
        build: ./client
        ports:
            - 8080:80
        environment:
            - API_HOST=http://localhost:8081
        networks:
            - dev
    server:
        build: ./server
        ports:
            - 8081:8080
        networks:
            - dev
    db:
        image: dwmkerr/dynamodb:latest
        command: -dbPath /data/
        volumes:
          - ./run/db:/data/
        ports:
          - 8000:8000
        networks:
          - dev

networks:
    dev:
        driver: bridge
        attachable: true
